version: "3.9"

name: vectoradmin

networks:
  vector-admin:
    driver: bridge

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5433:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: vectoradmin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vdbms
    networks:
      - vector-admin

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - vector-admin

volumes:
  qdrant_data:
